### PR TITLE
Updated compatibility info

### PR DESCRIPTION
**Pull request by elleryalvarez**

### CODE REVIEW

**Comment by brondsem** [comment]
The python 3.12 build failed on `formencode` trying to import `pkg_resources`.  I did some googling about pkg_resources and python 3.12 and found:

- https://docs.python.org/3/whatsnew/3.12.html says it changed:
> Do not pre-install setuptools in virtual environments created with [venv](https://docs.python.org/3/library/venv.html#module-venv). This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the [activated](https://docs.python.org/3/library/venv.html#venv-explanation) virtual environment.

- other people have run into similar issues with other packages too, for example https://github.com/microsoft/azure-devops-python-api/issues/470

So we probably need `ming` to have `setuptools` listed as a dependency.  It'd be better if `formencode` declared its dependency on `setuptools` but it doesn't :(

**Comment by amol-** [comment]
@brondsem I'll try to get this into Formencode itself, Ming is not the only library depending on formencode for validation so it would probably benefit a wider audience of projects if the change is upstreamed.

**Comment by amol-** [comment]
Actually it seems this is not happening in formencode master https://github.com/formencode/formencode/actions/runs/6497564616/job/17646958673?pr=180#step:4:25

**Comment by brondsem** [comment]
In that output I see `Collecting setuptools (from pycountry->-r requirements-test.txt (line 4))` so I think its getting it from there

**Comment by amol-** [comment]
> In that output I see `Collecting setuptools (from pycountry->-r requirements-test.txt (line 4))` so I think its getting it from there

That happens after formencode was already installed.  My understanding is that the issue reported was that it couldn't even install

**Comment by brondsem** [comment]
Here's the error we encountered: https://github.com/TurboGears/Ming/actions/runs/6462007528/job/17543400479#step:6:741 It was at runtime, after installation.

**Comment by amol-** [comment]
@brondsem Formencode 2.1 was release that should address this problem. Can you confirm the error wouldn't happen again even without the explicit setuptools dependency in Ming?

**Comment by brondsem** [comment]
Yep, it works, nice!

Tested with python3.12 `pip install Ming==0.13.0 'formencode<2.1'` errors on `python -c 'import ming; ming.config.configure(**{"ming":{}})'` but with `pip install Ming==0.13.0 'formencode==2.1'` it works fine.

**Pull request merged**
